schema_version: v0.0.1

application:
  name: AutoApp
  description: AutoAppDescription
  appConfig:
    version: 1
  artifacts:
    - name: CDN_Container_Image
      id: 3e9f0abf-c768-499d-8c46-5788888222dc
      containerImage:
        provider: custom_registry
        repo: cldcvr/cdn
        reference: latest
  creds:
    - credsType_aws
    - credsType_github